### ISSUE TITLE
Can't build with GCC 6.3.1 (20170306)

### ISSUE THREAD

**Issue by Megaxela** [louis-langholtz/Box2D#18]
I'm using archlinux and GCC 6.3.1, when I'm trying to build project I'm getting this output:
```
[  1%] Building CXX object Box2D/CMakeFiles/Box2D.dir/Dynamics/Contacts/Contact.cpp.o
In file included from /home/megaxela/Development/Build/Box2D/Box2D/Box2D/Dynamics/Contacts/Contact.cpp:22:0:
/home/megaxela/Development/Build/Box2D/Box2D/Box2D/../Box2D/Collision/DistanceProxy.hpp: In constructor 'constexpr box2d::DistanceProxy::DistanceProxy(box2d::Length, box2d::Length2D)':
/home/megaxela/Development/Build/Box2D/Box2D/Box2D/../Box2D/Collision/DistanceProxy.hpp:136:43: error: call to non-constexpr function 'std::array<_Tp, _Nm>::value_type& std::array<_Tp, _Nm>::operator[](std::array<_Tp, _Nm>::size_type) [with _Tp = box2d::Vector2D<float>; long unsigned int _Nm = 2ul; std::array<_Tp, _Nm>::reference = box2d::Vector2D<float>&; std::array<_Tp, _Nm>::value_type = box2d::Vector2D<float>; std::array<_Tp, _Nm>::size_type = long unsigned int]'
   const Length2D* m_vertices = &m_buffer[0];
                                           ^
/home/megaxela/Development/Build/Box2D/Box2D/Box2D/../Box2D/Collision/DistanceProxy.hpp: In constructor 'constexpr box2d::DistanceProxy::DistanceProxy(box2d::Length, box2d::Length2D, box2d::Length2D)':
/home/megaxela/Development/Build/Box2D/Box2D/Box2D/../Box2D/Collision/DistanceProxy.hpp:136:43: error: call to non-constexpr function 'std::array<_Tp, _Nm>::value_type& std::array<_Tp, _Nm>::operator[](std::array<_Tp, _Nm>::size_type) [with _Tp = box2d::Vector2D<float>; long unsigned int _Nm = 2ul; std::array<_Tp, _Nm>::reference = box2d::Vector2D<float>&; std::array<_Tp, _Nm>::value_type = box2d::Vector2D<float>; std::array<_Tp, _Nm>::size_type = long unsigned int]'
/home/megaxela/Development/Build/Box2D/Box2D/Box2D/../Box2D/Collision/DistanceProxy.hpp: In constructor 'constexpr box2d::DistanceProxy::DistanceProxy(box2d::Length, const box2d::Span<const box2d::Vector2D<float> >&)':
/home/megaxela/Development/Build/Box2D/Box2D/Box2D/../Box2D/Collision/DistanceProxy.hpp:92:29: error: call to non-constexpr function 'box2d::Span<T>::data_type* box2d::Span<T>::begin() const [with T = const box2d::Vector2D<float>; box2d::Span<T>::pointer = const box2d::Vector2D<float>*; box2d::Span<T>::data_type = const box2d::Vector2D<float>]'
    m_vertices{vertices.begin()},

```

**Comment by louis-langholtz** [comment]
@Megaxela Sorry about this. I'm really excited though that you've tried building it. I get the codebase to build on the continuous integration linux VM but clearly it's not building for you. I'll check now to look into why it's not. The part of the error message saying "non-constexpr" has me wondering if the problem is the inconsistent compiler support for `assert` in `constexpr` functions in C++14. One sec...

**Comment by louis-langholtz** [comment]
From the CI build log: The CXX compiler identification is Clang 3.7.1. So that's what I'm getting the code to build with on linux. If you have that version of Clang (or newer) available to you, I suspect it should build with that for you. It builds under Apple's Mac OS X clang also (of course that'd be for Mac OS X and you're trying to get a build on a linux box).

I'll try to do a build with gcc-5 and upward on the CI machine to see what happens with it. GCC 6.3 looks to be the newest release of GCC. I'd really like the codebase to build with at least the latest GCC suite and not just with clang.

**Comment by Megaxela** [comment]
Ok, I'll try it when I'll be able to reach my laptop with project. Thank you for fast response!

**Comment by louis-langholtz** [comment]
I see what the problem is now. GCC's uptake of `constexpr` seems to be behind clang's at least w.r.t. the standard C++ library header `<array>`for whether `const` reference `[]` access to std::array is `constexpr` or not. That's a bummer to me. Gonna be a while then for me to work-around that.

**Comment by louis-langholtz** [comment]
I got the g++ `constexpr` issues worked around now through changes to the source codebase.

The CI build then went on to report problems in the unit testing. These seem to be due to [a bug in g++: Stack corruption on ARM when using high registers and __builtin_return_address](https://gcc.gnu.org/bugzilla/show_bug.cgi?id=77933).

Switching CMAKE from doing a Release build to do a Debug build when building with the g++ compiler made the unit test reported problems go away consistent with the g++ bug report being attributed to having optimization enabled (specifically `-O1`). I believe that using a 6.3 gcc build would also work around this problem but I haven't found a `ppa` for gcc 6.3 yet that I can test this theory with.

Please let me know if you can build the codebase now with your installed gcc 6.3 and if you wouldn't mind, also run the unit tests and let me know what failures (if any) they report.

And thank you again for reporting this problem!

**Comment by Megaxela** [comment]
Ok, now I'm going to work, so when I'm reach the office I'll try to build this version.

**Comment by Megaxela** [comment]
Ok, I built this codebase successfully with -DCMAKE_BUILD_TYPE=Debug. (With release I'm getting error, that `argument to «-O» should be a non-negative integer, «g», «s» or «fast»`, but as I see that was expected.
Also I run unit tests and got 410 tests run successfully (out of 414).
Failed tests are:
```
[  FAILED  ] Dump.OneBodyWorld
[  FAILED  ] StackAllocator.slower_than_mallocfree
[  FAILED  ] World.ByteSize
[  FAILED  ] World.TilesComesToRestInUnder7secs
```

I'm runing on pretty slow PC (2 core pentium) so some tests that calculating execution time failed. But `World.ByteSize` error message:
```
Box2D/UnitTests/World.cpp:47: Failure
      Expected: sizeof(World)
      Which is: 400
To be equal to: size_t(376)
      Which is: 376
```

And pretty strange result in `Dump.OneBodyWorld`: see issue #19 for details.

**Comment by Megaxela** [comment]
And I got another question. I tried to build testbed and realized that some CMakeLists in project deprecated a little. Can I post pull requests, or your fork is not open contib?

**Comment by louis-langholtz** [comment]
@Megaxela I've taken the liberty of editing your comment regarding `Dump.OneBodyWorld` by creating a separate issue (issue #19 ) to track it and moving the data you've provided for that over to it. Also, I took the liberty of creating an issue for your question about open contrib (issue #20 ), creating another issue for some CMakeLists being "deprecated a little" (issue #21 ), and then deleted the comment where you'd raised that point and question (since they have there own issues now). Hope that's cool by you.

**Comment by louis-langholtz** [comment]
@Megaxela from what I read on the gcc bugzilla page, it appeared that gcc-6.3 shouldn't have the stack corruption bug in it so I'd presumed it would build the project with `-DCMAKE_BUILD_TYPE=Release` just fine. Sounds like you're reporting that the CMake you have, on trying to build Release, is trying to enable optimization by passing the capital-O letter flag to the compiler but the compiler is complaining that the flag requires a number like `1` (or one of the letters referenced) being appended to it (as in `-O1`). Is this a bug in CMake or a change to gcc that CMake isn't up to speed on?

**Comment by louis-langholtz** [comment]
The timing-based unit tests, I am rethinking. They don't make as much sense when they have a hard-coded time limit in them as when they compare one algorithm to another especially when run across different platforms.

**Comment by Megaxela** [comment]
I guess that problem with Release building on GCC is on this [line](https://github.com/louis-langholtz/Box2D/blob/dev/Box2D/CMakeLists.txt#L18) of CMakeLists code. GCC doesn't know about this optimization. What does it intend to do? When I removed this optimization I got project built successfully.

**Comment by louis-langholtz** [comment]
Nice find about the `-Ot` option! I'd forgotten even that I'd set that. It's a [clang command line option](https://clang.llvm.org/docs/UsersManual.html#command-line-options) that means: optimize for speed (lower time of execution). I hadn't realized it wasn't also supported on gcc. Switched it now to using `-O3` which hopefully works well for both compilers.

**Comment by Megaxela** [comment]
I guess it's solved for now. It's building fine.
